In [ ]:
#ex-1

import numpy as np

narray = np.array([1, 2, 3, 4, 5])

npmatrix = np.array([narray, narray, narray, narray])

print(npmatrix)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
#ex-2

import numpy as np
from numpy import random

arr = random.randint(100, size=(6))

print(arr)

[15 78 14 26 66 37]


In [ ]:
#ex-3

import numpy as np

narray = np.array([1, 2])

npmatrix = np.array([narray, narray, narray])

print(npmatrix)
print("Transposed Matrix:")
print(npmatrix.T)

print("-------------------")

narray2 = np.array([1, 2, 3])
squareMat = np.array([narray2, narray2, narray2])

print(squareMat)
print("Determinant of a Martix:")
det = np.linalg.det(squareMat)
print(det)

[[1 2]
 [1 2]
 [1 2]]
Transposed Matrix:
[[1 1 1]
 [2 2 2]]
-------------------
[[1 2 3]
 [1 2 3]
 [1 2 3]]
Determinant of a Martix:
0.0


In [ ]:
#ex-4

import numpy as np
from numpy import random

arr = np.random.randint(1,100, (5,4))

print(arr)



[[40 44 30 55]
 [ 5 71 20 62]
 [99 30 63 27]
 [64 97 54  9]
 [97  4  7 17]]


In [ ]:
#ex-6

import numpy as np

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,3,2], [7,8,9]])

mul = arr1 * arr2

print(mul)

[[ 4  6  6]
 [28 40 54]]


In [ ]:
#ex-5

import numpy as np

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,3], [7,8], [5,6]])

result = np.dot(arr1,arr2)
print(result)

[[33 37]
 [81 88]]


In [ ]:
#ex-7

import numpy as np

narray = np.array([1, 2, 3, 4, 5, 6])

mean = np.mean(narray)

print(mean)

3.5


In [ ]:
#ex-8

import numpy as np

arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr1[0:,1])

[2 5 8]


In [4]:
#ex-9

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('https://raw.githubusercontent.com/ayarn/CE084_Ayarn_Modi_ML-Lab/master/Iris.csv')

arr1= np.array(data['Id'])
nparrayCentered = arr1 - np.mean(arr1)
print("For ID:\n", nparrayCentered)

arr1= np.array(data['SepalLengthCm'])
nparrayCentered = arr1 - np.mean(arr1)
print("For SepalLengthCm:\n", nparrayCentered)

arr1= np.array(data['SepalWidthCm'])
nparrayCentered = arr1 - np.mean(arr1)
print("For SepalWidthCm:\n",nparrayCentered)

arr1= np.array(data['PetalLengthCm'])
nparrayCentered = arr1 - np.mean(arr1)
print("For PetalLengthCm:\n",nparrayCentered)

arr1= np.array(data['PetalWidthCm'])
nparrayCentered = arr1 - np.mean(arr1)
print("For PetalWidthCm:\n",nparrayCentered)

For ID:
 [-74.5 -73.5 -72.5 -71.5 -70.5 -69.5 -68.5 -67.5 -66.5 -65.5 -64.5 -63.5
 -62.5 -61.5 -60.5 -59.5 -58.5 -57.5 -56.5 -55.5 -54.5 -53.5 -52.5 -51.5
 -50.5 -49.5 -48.5 -47.5 -46.5 -45.5 -44.5 -43.5 -42.5 -41.5 -40.5 -39.5
 -38.5 -37.5 -36.5 -35.5 -34.5 -33.5 -32.5 -31.5 -30.5 -29.5 -28.5 -27.5
 -26.5 -25.5 -24.5 -23.5 -22.5 -21.5 -20.5 -19.5 -18.5 -17.5 -16.5 -15.5
 -14.5 -13.5 -12.5 -11.5 -10.5  -9.5  -8.5  -7.5  -6.5  -5.5  -4.5  -3.5
  -2.5  -1.5  -0.5   0.5   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5
   9.5  10.5  11.5  12.5  13.5  14.5  15.5  16.5  17.5  18.5  19.5  20.5
  21.5  22.5  23.5  24.5  25.5  26.5  27.5  28.5  29.5  30.5  31.5  32.5
  33.5  34.5  35.5  36.5  37.5  38.5  39.5  40.5  41.5  42.5  43.5  44.5
  45.5  46.5  47.5  48.5  49.5  50.5  51.5  52.5  53.5  54.5  55.5  56.5
  57.5  58.5  59.5  60.5  61.5  62.5  63.5  64.5  65.5  66.5  67.5  68.5
  69.5  70.5  71.5  72.5  73.5  74.5]
For SepalLengthCm:
 [-0.74333333 -0.94333333 -1.14333333 -1.24333333 -0.84333

In [1]:
#ex-10

import numpy as np
matrix = np.array([[1,1,1],[2,2,2],[3,3,3]])
matrix1 = np.array([[1,2,3],[3,4,5],[4,3,1]])
print('Original matrix:\n',matrix)

print('Transposed matrix:\n',matrix)

print('Norm:\n',np.linalg.norm(matrix))

print('Multiplication of two matrix:\n',np.dot(matrix,matrix1))

print('Sum:\n',np.sum(matrix * matrix1))

print('Matrix mean:\n',np.mean(matrix))
print('Mean by columns:\n',np.mean(matrix,axis=0))
print('Mean by rows:\n',np.mean(matrix,axis=1))

matrixCentered = matrix-np.mean(matrix, axis=0)
print('Centered by columns matrix:\n',matrixCentered)
print('New mean by column:\n',matrixCentered.mean(axis=0))

Original matrix:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Transposed matrix:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Norm:
 6.48074069840786
Multiplication of two matrix:
 [[ 8  9  9]
 [16 18 18]
 [24 27 27]]
Sum:
 54
Matrix mean:
 2.0
Mean by columns:
 [2. 2. 2.]
Mean by rows:
 [1. 2. 3.]
Centered by columns matrix:
 [[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
New mean by column:
 [0. 0. 0.]
